spring.application.name=SpringSecurity-JWT
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/pg_lab_dev
spring.datasource.username=jottaDev
spring.datasource.password=jottaDev.1234

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update